canonical/sphinx-docs-starter-pack

- .sphinx/requirements.txt
- conf.py
To provide a preview on other websites or on Mattermost.
> add OpenGraph metadata

- .sphinx/spellingcheck.yaml
- .wordlist.txt
- doc-cheat-sheet.rst
- readme.rst
Cutting down the cheat sheet from a style guide to an actual cheat sheet.
> Cheat sheet v2

- Makefile
(The GitHub workflow uses the get-woke/woke-action@v0 action.)
> add a Makefile target for running woke

- conf.py
- doc-cheat-sheet.rst
- reuse/links.txt
Several small changes to the doc cheat sheet.
> Update the doc cheat sheet

- .sphinx/requirements.txt
- .wordlist.txt
- conf.py
- doc-cheat-sheet-myst.md
- how-to/index.rst
- how-to/markdown.md
Output for the cheat sheet: https://canonical-starter-pack--24.com.readthedocs.build/doc-cheat-sheet-myst/?next=https%3A%2F%2Fcanonical-starter-pack--24.com.readthedocs.build%2F&ticket=ST-1682609583-YkrrLPlAJMf2zLxoiCrgJoUuuBRyrE2n
> Add MyST support

- .sphinx/_templates/footer.html
- conf.py
- readme.rst
Several closely related fixes for the links in the footer - see the separate commits for more detail.
> Issue link

- readme.rst
conf.py does not have the github_filetype setting anymore.
> Update readme to remove an outdated instruction 

- readme.rst
Added section to readme advising user to run various local checks. Close #89.
> Local checks

- .gitignore
- .sphinx/_static/furo_colors.css
- .sphinx/_templates/base.html
- Makefile
- conf.py
Not a huge change when looking at the size of the starter pack, but for bigger doc sets this reduction can make a difference.
Fixes #92 .
> Reduce size

- readme.rst
> update information about pinned requirements

- conf.py
- custom_conf.py
> make the sidebar title configurable

- .wordlist.txt
- readme.rst
> add a list of included extensions

- custom_conf.py
Add a few more comments to make it clearer what needs to be updated and how.
Fixes #114.
> add more explanation to custom_conf.py

- readme.rst
As discussed in
https://github.com/canonical/sphinx-docs-starter-pack/pull/87#discussion_r1355111592
> move note about updating the starter pack files

- readme.rst
I updated the RTD link to library links as it was double-redirecting. I also added links to the example repository and its documentation as additional resources.
> Update link and add resources

- .sphinx/_templates/footer.html
> Change master_doc to root_doc

- Makefile
> fix: inconsistent help text of Makefile

- custom_conf.py
- readme.rst
> Document sequential_nav

- doc-cheat-sheet-myst.md
- doc-cheat-sheet.rst
This follows the respective PR: canonical/canonical-sphinx-extensions#34
> update terminal directive usage

- conf.py
> find the root of the GitHub repository to determine contributors

- .wordlist.txt
Minor change; but Numbat fails the spell check. =)
> Added Numbat to wordlist

- .readthedocs.yaml
This is needed to make all contributors show up.
> fetch the full Git history

- init.sh
added rm -rf ".github" so that it removes .github in the parent directory once the mv command is done
> init.sh leaves empty workflows directory #235

- .sphinx/_static/custom.css
- .sphinx/_static/furo_colors.css
This addresses canonical/sphinx-docs-starter-pack#230.
> tone down link underlines

- .github/workflows/sphinx-python-dependency-build-checks.yml
- Makefile.sp
- init.sh
- readme.rst
Please review/merge commit by commit.
Fixes #238
> Add check for Sphinx build dependencies, consequently documenting them

- sp-files/.sphinx/_templates/header.html
Update the header file to include all related resources that are specified in the conf.py file.
The header file really lives in the canonical-sphinx extension, but it is included here as well to make it easy to customise. I'll open a PR to add the changes to canonical-sphinx as well.
> update the header file

- .github/workflows/automatic-doc-checks.yml
- sp-files/.github/workflows/automatic-doc-checks.yml
* Refine triggers to avoid replicated runs on PRs
* Remove branch restriction for PR trigger
(Cherry-pick from main branch.)
> Refine triggers to avoid replicated runs on PRs (#267)

- docs/content/set-up.rst
> Update language to use "download" instead of "clone"

- docs/.custom_wordlist.txt
- docs/Makefile
- docs/conf.py
- docs/content/automatic_checks_inclusivelanguage.rst
- docs/reuse/links.txt
Adds functionality and documentation for replacing Woke with Vale rules.
Adds env variable to pass different Vale config.
Closes #321 and #331
> Feat: Configurable Vale command + replacement of Woke

- docs/Makefile
> Remove Makefile.sp target

- docs/Makefile
Present in older Makefile.sp but not in current Makefile
> Remove redundant phony target

- docs/conf.py
> conf: drop spurious `ast` import

- CHANGELOG.md
- docs/.sphinx/update_sp.py
> fix: spelling mistake in update script

- .github/workflows/check-removed-urls.yml
- CHANGELOG.md
Fixes #436
-----
I don't see any relevant documentation for this change so I have only updated the changelog.
> fix(ci): make check-removed-urls work with private forks
