canonical/sphinx-docs-starter-pack

Makefile
This doesn't change anything for the read-the-docs build, but it gives the same output locally as on read the docs.
=> change buildtype for local builds to dirhtml

conf.py, reuse/links.txt
All links defined in the reuse/links.txt file are available in all documentation pages in the project.
=> add a file for common links

.sphinx/_static/custom.css, doc-cheat-sheet.rst
Forcing the alignment in table cells to always center can lead to undesired output.
For example:
Instead, leave the default at left-aligned, but allow to center-align using reST syntax (examples added to the cheat sheet).
=> allow adjusting the table alignment

.readthedocs.yaml
Currently it is a minimal file, needed to avoid a recent RTD build error (https://github.com/readthedocs/readthedocs.org/issues/10290).
=> Provide default RTD configuration by adding a readthedocs.yaml file.

.readthedocs.yaml
Update the configuration file with the default configuration - mainly the builder (dirhtml) and the formats we want to generate (only PDF in addition to HTML).
Closes #26.
=> add default configuration to readthedocs.yaml

.github/workflows/automatic-doc-checks.yml, readme.rst
That makes it easier to adapt the jobs if the docs are in a different directory.
=> explicitly add the working directory to the GitHub action

.wordlist.txt, readme.rst
I am going through the process of integrating the starter pack into a code repository and I found the current instructions unnecessarily confusing. Since the nature of the starter pack is to make available RTD in a consistent manner across the company I went ahead and made the instructions (on this particular topic) more prescribed and therefore much clearer. General improvements in terms of clarity and RST-native formatting were also made.
I also made the lines extend to a maximum of 79 characters as is "good & proper". :tm:
=> Make code repo setup more prescribed

reuse/links.txt
This PR fixes two links that were pointing to library.canonical.com . The `linkcheck` make job may not able to detect broken links to that domain due to 2FA.
There was also a link that used a URL shortener which is not best practice.
=> Fix and improve links

conf.py, custom_conf.py, readme.rst
Put the common configuration in one file and all project-specific configuration into another one, so that users can easily update the common configuration while keeping their customisations. This also makes it much easier to update the project-specific configuration.
Fixes #39 and #47.
=> split the configuration file into common and custom

conf.py
Make sure we don't get a font error if someone comments out ogp_image. See https://github.com/wpilibsuite/sphinxext-opengraph/issues/107
Fixes #42.
=> add a default for ogp_image to prevent a font bug

.sphinx/_templates/header.html, custom_conf.py
If RTD is configured for multiple versions, it adds an automatic redirect to /en/latest, which messes up linking to anything at root level.
=> fix path to the tag in the header

readme.rst
Include a sample Git workflow for importing the pack into a dedicated documentation repository.
Make all the lines in section "Standalone documentation repository" a maximum of 79 characters, as is good and proper :tm:
=> Add sample git workflow for dedicated docs repo

readme.rst
In particular, GitHub does not support RST admonishments.
=> Small readme improvments

.sphinx/requirements.txt, conf.py, custom_conf.py
Fixes #51.
Unfortunately, the page doesn't display right in the preview (because that uses a different URL structure than the real docs). I tested the paths though, and I'm positive they are correct. :)
=> add a custom 404 page

.github/workflows/automatic-doc-checks.yml, Makefile
- Replace woke command in GitHub action with call to existing make woke
- Makefile needs sudo to install Snap if woke missing
- Missing-woke problem solved by sudo snap install; no need for error exit
- [Jira](https://warthogs.atlassian.net/browse/DOCPR-55)
=> feat: refactor woke for SSoT

custom_conf.py
Links:
- <https://www.copyrightlaws.com/copyright-symbol-notice-year/>
=> add comment on copyright notice format to custom_conf.py

Makefile
The repo that contains it has moved:
https://github.com/canonical/Inclusive-naming/
=> update woke config URL

.sphinx/requirements.txt
The bugs are fixed, so we can unpin the Sphinx version again :)
=> unpin the Sphinx version again

.wordlist.txt, readme.rst
- After refactoring, woke's now launched from one place only
- GitHub doesn't render "---" as em-dashes
=> update readme: woke in Makefile only

conf.py, custom_conf.py
Users might want to add more URLs for which the anchors are ignored, so add a custom variable for this.
We should ignore GitHub globally, since those anchors are handled in a way the linkchecker can't deal with, so this will be an issue for all doc sets.
=> allow customising linkcheck_anchors_ignore_for_url

.sphinx/_templates/footer.html, custom_conf.py
Closes #94.
Added new custom variable. 4 options for controlling sequential nav buttons.
To test:
- `make run`
- Play around with different values for the `sequential_nav` option in `cutom_conf.py` - "both", "none", "next", "prev" - and see the effect on the buttons. Note: an unexpected value like "blah" should be treated as "none"
=> Optional nav

conf.py, custom_conf.py
There might be projects (like LXD ...) that have a "doc-cheat-sheet*" file as part of their documentation.
Therefore, we shouldn't exclude this file in conf.py (which projects shouldn't modify), but in custom_conf.py.
=> don't totally exclude `doc-cheat-sheet*`

.sphinx/spellingcheck.yaml, readme.rst
Project-specific jargon should go here. This prevents collisions with updates to common wordlist. Closes #108.
- Make spelling - should pass (confirming no regression of happy case)
- Modify `readme.rst` with some fake non-word like “nonwordicus”
- Make spelling - should fail (confirm no regression of failure case)
- Update the custom wordlist with the same fake non-word e.g. “nonwordicus”
- Make spelling - should now pass (confirming new functionality works)
=> Custom wordlist

.sphinx/_static/github_issue_links.js
If another JavaScript already defines a window.onload function, including the `github_issue_links.js` script will overwrite that function.
To prevent this, save the function that is already defined (if there is none, it'll just be empty, so no problem) and add it back as part of the function we're defining.
=> prevent overwriting existing window.onload functions

Makefile
Causes a non-zero exit status when there are findings.
To test locally:
1. Checkout `main` branch
2. Edit some file to include a disallowed word (e.g. edit `readme.rst` by adding "master")
3. Run `make woke`
4. Observe that there is a "finding" reported by woke, warning of the use of the disallowed word
5. Run `echo $?` immediately afterwards - it should output `0`, indicating successful exit status
Repeat the above steps again on this branch. Notice that the command exits with non-zero exit status this time.
=> Exit 1 on failure

Makefile
Fixes #122 
This adds:
* Sourcing of the `activate` script in the command of the `help` target, so that the `sphinx-build` script is in the PATH and can be executed.
* The `$(VENVDIR)` target as a prereq to the `help` target, so that `make help` doesn't fail when run without some other target first creating the virt. env.
=> Fix 'help' target

.sphinx/spellingcheck.yaml
Commands that are marked up with ``:command:`abc` `` in rST should not be checked by the spelling checker.
=> spelling check: exclude commands

Makefile
Fixes #130 & [DOCPR-179](https://warthogs.atlassian.net/browse/DOCPR-179)
* Adds indentation to multi-line commands
* Removes line breaks in commands where not needed
* Removes empty lines where not needed
* Puts all PHONY targets on one line
* Adds info about the `linkcheck` target
[DOCPR-179]: https://warthogs.atlassian.net/browse/DOCPR-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reformat Makefile for readability

init.sh, readme.rst
When running woke locally, the .wokeignore file must be in the folder where you run it (for example, the `docs` folder). When runnin on GitHub, we run woke from the root folder though, and it cannot deal with a .wokeignore file in a subdirectory. Therefore, have the script create a symlink (unless there already is a .wokeignore file in the root folder).
=> init script: create link for .wokeignore

init.sh
We removed the file from the starter pack, so need to remove it from the setup script as well.
=> remove handling of .jira_sync_config.yaml from the setup script

readme.rst
Clarify where the spelling check configuration is, but don't call out that you can change the language to en_US anymore.
=> update spelling check configuration information

.sphinx/_static/custom.css
Code-block copybutton invisible by default (overriding Furo config to achieve default copybutton setting).
Fixes #145
=> Make code-block copybutton invisible

.sphinx/_templates/footer.html, .wordlist.txt, custom_conf.py
This closes issue #61 on GitHub.
=> add Mattermost linking mechanism

readme.rst
This PR adds a note in Readme about how to resolve locale errors when activating the Python virtual environment. Some users may encounter a Python locale error when they use `make run`. This might be caused by the system environment variable `locale.LC_ALL` being empty. Adding the locale setting as a prefix in the make command resolves this issue.
(Users may also choose to change this environment variable for their local dev environment, but there is a risk of causing other conflicts.)
Error stack trace reported by a team member:
```
. .sphinx/venv/bin/activate; sphinx-autobuild -b dirhtml "." "_build" -c . -d .sphinx/.doctrees
[sphinx-autobuild] > sphinx-build -b dirhtml -d .sphinx/.doctrees -c . /home/user/code/hexr/docs /home/user/code/hexr/docs/_build
Traceback (most recent call …
```
=> add note about fixing Python locale error

.sphinx/_static/custom.css, .sphinx/_static/furo_colors.css
This PR adds `@font-face` definitions based on Vanilla to include latest Ubuntu variable web font, and uses this font in font config. This should fix the issue with wrong weight of the Ubuntu font and align this better with Vanilla styling.
Part of WEBDOC-7
=> Add new Ubuntu variable font to custom CSS

.sphinx/_static/custom.css
See https://github.com/canonical/sphinx-docs-guide/pull/22 / https://canonical-documentation-with-sphinx-and-readthedocscom.readthedocs-hosted.com/style-guide/#glossary for how it looks in the output.
=> fix the styling of inline code

doc-cheat-sheet-myst.md
Fix syntax error -  target name (string between parenthesis) and the reference link did not match.
Also, since the target name "a_section_target" has been defined in RST, so I added a suffix to illustrate that targets in RST and MyST should not duplicate.
=> fix target name in myst cheat sheet

custom_conf.py
Redirects can be configured with the ReadTheDocs admin dashboard. No project side redirects required.
See https://docs.readthedocs.io/en/stable/guides/redirects.html
=> docs: add remark about Read the Docs redirects

.sphinx/_static/custom.css
Make the styling more similar to current Vanilla, and make it work for both sphinx-tabs and sphinx-design tabs.
See also https://github.com/canonical/sphinx-docs-guide/pull/23
=> fix the styling for tabs

readme.rst
This elaborates on the installation prerequisites in the contributors section and adds `pa11y` to the check lists for completeness, improving consistency in the process.
=> chore: add prerequisites, pa11y check to README

.readthedocs.yaml, .sphinx/build_requirements.py, Makefile, conf.py, init.sh, readme.rst
The script shouldn't be on the root level, since users don't need to know about it.
Adresses #183
=> move build_requirements.py to .sphinx folder

.sphinx/_static/custom.css
The font size for admonitions is smaller than the normal font size. Make sure that inline code in admonitions displays at the same (smaller) size.
=> fix font size for code in admonitions

conf.py
This moves the `notfound_template = '404.html'` setting to conceal it from any builders other than `html` and `dirhtml`.
Fixes #204.
=> Hide notfound_template from epub builder

.sphinx/_templates/footer.html, .wordlist.txt, custom_conf.py
Juju/Ops Framework use Matrix instead of Mattermost, would be nice if the template supports Mattermost.
Closes https://github.com/canonical/sphinx-docs-starter-pack/issues/206.
=> feat: support Matrix link in footer

Makefile
`-j auto` makes the Sphinx build use all CPUs.
=> speed up the Sphinx build

.sphinx/build_requirements.py
Adds the `watchfiles` module to `build_requirements.py` to fix #213.
=> Add the 'watchfiles' module for sphinx-autobuild

conf.py
https://github.com/canonical/sphinx-docs-starter-pack/pull/203 introduced a function into the `html_context` configuration. In parallel, a Sphinx update added a warning message for such cases (see https://github.com/sphinx-doc/sphinx/issues/12300).
This commit suppresses the new warning for now.
We might be able to find a better solution later.
=> suppress warning about config caching

.readthedocs.yaml, Makefile.sp, conf.py, custom_conf.py
The Ubuntu manpage urls return a "404 Not Found" error, because when verified by linkcheck the JavaScript code that will look up the searched manpage at runtime does not get executed.
To solve this error we staticaly define the URL that would otherwise be looked up at runtime. Therefore we use dist-info to look up the latest Ubuntu distribution.
One drawback is that the documentation has to periodically be regenerated, because a newer Ubuntu distribution will be released every 6 months.
Bug: #224
=> fix: manpage url linkcheck failures

.sphinx/_static/furo_colors.css
Use the colour that Vanilla uses for dark mode:
https://vanillaframework.io/docs/patterns/links#dark
See https://github.com/canonical/lxd/issues/13062
=> fix colour for links in dark mode

.readthedocs.yaml
Changing the build job to `pre_install` for the `build_requirements.py` script means that the build machine will already be fully set up, so that you can use pip to install any packages that are required in `custom_conf.py` and will otherwise give errors.
This is required to work around #197.
=> change build job for build_requirements.py

readme.rst
Updated the README instructions ~~to work for docs-in-code repository workflow (related to issue #232), and~~ to indicate other prerequisite packages / software to account for new users who are possibly working with these repositories for the first time.
Added @giuliazanchi who also went through some pains to get things up and running for the first time.
Other updates are formatting / syntax related updates.
Thanks!
Note: `InvalidGitRepositoryError` will be fixed in PR https://github.com/canonical/sphinx-docs-starter-pack/pull/229 .
=> Update readme for docs in code flow

.readthedocs.yaml, Makefile.sp, conf.py, custom_conf.py
For the basic functionality of the starter pack, we should not assume that we are on Ubuntu.
Therefore, undo the change of automatically determining the manpages URL (instead, add the variable to `custom_conf.py` so every team that needs it can decide if they want to update it manually or add some automatic processing).
Also, don't automatically install python3-env if it's missing, but return an error message that it must be installed.
=> Get rid of apt install in the Makefile

Makefile, Makefile.sp, doc-cheat-sheet-myst.md, readme.rst
Several small improvements to our Makefile targets - see the separate commits.
=> Build improvements

.wordlist.txt
Looks like `Dqlite` is preferred in [the docs](https://dqlite.io/docs).
=> spelling: Add Dqlite to wordlist

init.sh, sp-files/.sphinx/requirements.txt, sp-files/conf.py
This PR uses the updated canonical-sphinx-extensions (https://github.com/canonical/canonical-sphinx-extensions/pull/41) and the updated canonical-sphinx package (https://github.com/canonical/canonical-sphinx/pull/25).
=> Add contributor listing

.github/workflows/automatic-doc-checks.yml
The workflow currently runs twice on PRs, on every commit from a branch:
This is because the trigger branch for push event isn't restricted to main.
This isn't an issue on PRs with a forked repo head, only on those from an internal branch.
=> Refine triggers to avoid replicated runs on PRs

sp-files/Makefile.sp
This reverts commit 75412db9be3664171dc3f8365d0c7a7be95137b2.
https://github.com/canonical/canonical-sphinx/issues/27 should be fixed now (with https://github.com/canonical/canonical-sphinx/pull/43).
=> Revert "cannot do parallel builds for now"

.custom_wordlist.txt, .wordlist.txt, Makefile.sp
Some similar work will need to be done when the vale action is done by GitHub actions, but this works for now. I attempted some more complicated logic, but limitations with make brought me back to this relatively basic approach.
=> Adds project specific excludes to the make entrypoint

.github/workflows/test-starter-pack.yml, init.sh, sp-files/index.md
Adds a check to `init.sh` that determines whether the user wants to use `.md` or `.rst` files for their documentation.
If the user chooses one filetype the files of the other type will be removed from the target directory where the documentation is built (namely: the appropriate index file and cheat-sheet file).
The user input is validated and must be either `md` or `rst`.
If the user hits **ENTER** without specifying a filetype then it defaults to `rst`.
To make this work an `index.md` corresponding to the extant `index.rst` was added to the repo.
An env var was added to the starter-pack testsuite to prevent the interactive prompt running during testing.
DOCPR-836
=> User selects docs filetype

README.rst, init.sh, sp-files/contributing.rst
Changes the init script to pull from the main branch again...
=> fix: Update init.sh

.sphinx/pa11y-ci.json, .sphinx/pa11y.json, Makefile.sp
Main improvement: improved readability of logs, as well as "potential" performance improvements due to not having to launch `pa11y` for each file. In addition, `pa11y-ci` offers a concurrency option, but that seems to be broken at the moment.
`pa11y` output:
```
Welcome to Pa11y
> Running Pa11y on URL file:///home/tarek/code-projects/mir/doc/build_doc/doc/sphinx/_build/404/index.html
No issues found!
Welcome to Pa11y
> Running Pa11y on URL file:///home/tarek/code-projects/mir/doc/build_doc/doc/sphinx/_build/search/index.html
No issues found!
Welcome to Pa11y
> Running Pa11y on URL file:///home/tarek/code-projects/mir/doc/build_doc/doc/sphinx/_build/tutorial/index.html
Results for URL: file:///home/tarek/code-projects/mir/doc/build_doc/doc/sphinx/_build/tutorial/index.html
• Error: This …
```
=> Use pa11y-ci instead of pa11y

sp-docs/docs/customise.rst, sp-files/conf.py
The settings used to be part of `conf.py`.
Not sure if that was intentionally removed but it took me a bit of time to figure out where it should go.
=> Update instructions for sequential navigation

init.sh
Missing '/' causing default github workflow action to fail.
=> Fix sed command for markdownlint

sp-docs/docs/enable.rst
Added a missing step - the script asks users to specify if they'll use `.rst` or `.md`
=> Add missing step to specify file format

sp-docs/docs/rtd.rst, sp-docs/reuse/links.txt
The RTD at Canonical link was 404-ing, so I corrected it
=> doc: Update broken link

docs/conf.py
This includes a default of 3 retires on failure and then makes the timeout option more visible within the config file.
These are based on a fixing change to [MicroOVN](https://github.com/canonical/microovn/pull/207) where we were having instability in linkchecks.
=> Add smarter defaults for linkcheck.

docs/content/rtd.rst
Add missing `.` in example text: `doc/.readthedocs.yaml`.
=> doc: fix typo

.github/workflows/sphinx-python-dependency-build-checks.yml, .github/workflows/test-starter-pack.yml
These workflows run twice on PRs because the trigger for push events isn't restricted to main:
How to reproduce:
1. Open PR (this runs the checks once)
2. Push another commit (this will run the checks twice, for the `push` event & `pull_request`)
Similar to #267
=> fix: prevent repeated CI runs

docs/content/migrate-from-pre-extension.rst, docs/content/set-up.rst, docs/index.rst
Add key steps and resources required to migrate an existing project from an earlier *pre-extension* Sphinx Starter Pack to the extension-based version. 
(An earlier version of this document was edited in [Google doc](https://docs.google.com/document/d/1z__G0adpu_rXSUrdNNv-qeCd1CkJOTcKmD5t02ekl9I/edit?usp=sharing))
=> Add migration guide for pre-extension starter pack

.github/workflows/automatic-doc-checks.yml, .github/workflows/markdown-style-checks.yml, .readthedocs.yaml, docs/.sphinx/.pre-commit-config.yaml, docs/content/automatic_checks.rst, docs/content/rtd.rst
(Resolves [DOCPR-1420](https://warthogs.atlassian.net/browse/DOCPR-1420))
The Readthedocs build checks on pull requests should only be triggered when documentation changes are included. This prevents extra builds in repositories that contain both the source code and docs.
A triggering condition is introduced to `.readthedocs.yml` template to cancel build upon `git diff` result.  [Readthedocs documentation](https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition) added as comment
[DOCPR-1420]: https://warthogs.atlassian.net/browse/DOCPR-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: trigger readthedocs build only upon doc changes

docs/.sphinx/get_vale_conf.py, docs/Makefile
Current script does not obtain newly included dictionaries. Adds section to `docs/.sphinx/get_vale_conf.py` to obtain relevant files.
Changes filters used in Makefile's `vale-install` to provide separate style guide, inclusive language, and spelling check functions.
Provides a spelling function for testing and validation before replacing pyspelling.
=> fix: Vale operations

docs/content/rtd.rst, docs/reuse/links.txt
After I imported a new project into Read the Docs and set up the webhook, RTD build status wasn't visible as a check in GitHub. The issue was that the webhook wasn't set up by someone with admin privileges for the GitHub repo. Additionally, the admin first needed to connect their RTD account to GitHub.
This PR makes a couple of additions to [Set up Read the Docs](https://canonical-starter-pack.readthedocs-hosted.com/latest/content/rtd/) to remind people to check that their RTD account is connected to GitHub.
=> docs: add info about connecting GitHub accounts to Read the Docs

docs/conf.py
Adding a placeholder section in `docs/conf.py` for how to enable the edit button (per [Version 0.4.0](https://github.com/canonical/canonical-sphinx/releases/tag/0.4.0) of `canonical-sphinx`).
=> chore: doc config changes for canonical-sphinx 0.4.0

docs/Makefile
While the existing config works when the documentation is deployed to production via ReadTheDocs, it presents a new issue for contributors contributing to Canonical repos like the Ubuntu Server and Juju docs.
Personally, I struggled with this issue. I almost gave up on contributing to these repos because I couldn't access the built docs on my browser while also allowing it to automatically make changes as I go. This fix has made me overcome my struggle, and now I have 15 merged PRs across these repos.
Now, not all Canonical repos need this change. I didn't struggle with this when I worked on the Ubuntu cloud docs repo. Regardless, I still think this change will be important. It still retains the previous config which binds to localhost.
Relevant to juju/juju#19143 and …
=> Allow users optionally define which host IP address to bind

docs/conf.py
These are currently marked as f-strings, which they should not be. The {codename} substitution is for the docs author to replace, but {section} and {page} are templates that Sphinx itself will use and thus must be left in the string (not replaced by the f-string mechanism).
=> Fix substitutions in manpages_url

docs/Makefile
Using \n' in the 'echo' command is not portable.
In bash:
$ echo 'hello\n'
hello\n
$
In dash:
$ echo 'hello\n'
hello
$
The current code assumes the behavior of dash's built-in echo command. This is likely the case because GNU Make uses /bin/sh as the default shell, and /bin/sh is a symlink to dash by default on Ubuntu.
If a different shell (e.g., bash) is used, '\n' may not be interpreted as a newline, resulting in an unreadable message.
A more portable approach is either use the 'printf' command, or split the message across multiple 'echo' commands.
This commit adopts the latter.
=> Makefile: Do not use \n in echo

CHANGELOG.md, docs/how-to/contributing.rst, docs/how-to/guidance.rst, docs/reference/automatic_checks_spelling.rst, docs/reference/doc-cheat-sheet-myst.md, docs/reference/doc-cheat-sheet.rst, docs/reference/style-guide-myst.md, docs/reference/style-guide.rst, docs/reuse/links.txt
In preparation for archiving sphinx-docs-guide, I removed any links to the "canonical-documentation-with-sphinx-and-readthedocscom" RTD site and replaced those links with references to the style guides in this repo.
-----
=> Update links and references to style guides

docs/reference/style-guide-myst.md, docs/reference/style-guide.rst
This PR stores the short URL in the `related link` field, using the original link to avoid third-party stability and maintenance issues.
A third-party link in the `related link` header (a short URL pointing to the Sphinx documentation) causes the doc build to fail because its SSL certificate verification failed ([action run failure](https://github.com/canonical/sphinx-docs-starter-pack/actions/runs/14698551899/job/41243915097) and [RTD build failure](https://app.readthedocs.com/projects/canonical-starter-pack/builds/3002075/))
Error message during HTML build:
```
WARNING: reference/style-guide: HTTPSConnectionPool(host='tinyurl.com', port=443): Max retries exceeded with url: /rstprimer (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify …
```
=> Fix: update related links header to use Sphinx original URL

docs/.custom_wordlist.txt, docs/how-to/customise-pdf.rst, docs/how-to/index.rst, docs/reference/automatic_checks_inclusivelanguage.rst
(Resolves DOCPR-995)
Add a how-to guide for customizing PDF output in the documentation using Sphinx configuration and LaTeX template.
* Configure PDF document properties with Sphinx `latex_documents`, with explanation of the tuple elements
* Change PDF document filename
* Change PDF document title
* Use a different index document for PDF builds
* Override LaTeX template provided by the `canonical_sphinx` extension, using locally provided `latex_elements`
* Add more LaTeX packages to the preamble
* Remove the table of contents
* Include images or other assets
* Use landscape layout
* Check build log files for local debugging
Preview at: https://canonical-starter-pack--381.com.readthedocs.build/381/how-to/customise-pdf/
=> Doc: add instructions for configuring PDF output

docs/reference/doc-cheat-sheet-myst.md, docs/reference/doc-cheat-sheet.rst, docs/reference/style-guide-myst.md, docs/reference/style-guide.rst
-----
Previously, the style guide recommended using the [Sphinx tabs](https://sphinx-tabs.readthedocs.io/en/latest/) extension for creating tabs. The reason was that the tabs available from the [Sphinx design](https://sphinx-design.readthedocs.io/en/latest/) extension didn't synchronize across pages.
However, @edibotopic and I tested the tabs last week, and both extensions can now synchronize properly, removing the need for Sphinx tabs.
In addition, Sphinx tabs have their own issues:
- When you switch tabs, the tabs visually jump about a pixel to the left or right. Tested in Firefox and Chromium.
- They don't work in the PDF output. See #302.
- They require an additional extension.
Since Sphinx tabs don't seem to provide any benefits nowadays and only cause issues, I propose that we …
=> Switch the recommendation to Sphinx design tabs

docs/how-to/set-up-sitemaps.rst
When following the instructions to implement the sitemap, I ran into a
couple of places that confused me. I have added some clarification to those
places in the doc.
-----
=> Clarify instructions for sitemaps

CHANGELOG.md, docs/.sphinx/update_sp.py
-----
The update script didn't seem to be downloading the latest files, I think because the branch name wasn't set to `main`. This PR fixes that.
=> fix: branch name in update script

docs/how-to/edit.rst, docs/how-to/migrate-from-pre-extension.rst, docs/tutorial/set-up.rst
-----
The `docs/content` folder has been removed from the repository, replaced by the diataxis folders under `docs/`. This PR:
- removed the obsolete references to the `docs/content` folder to reflect the new structure
- changed the example page from `docs/reference.rst` to `docs/reference/settings.rst`
=> fix: remove references to obsolete docs/content/ directory

docs/conf.py, docs/how-to/set-up-sitemaps.rst
-----
Adds documentation for adding a `lastmod` date to the sitemap generated by sphinx-sitemaps.
Fixes sitemapindex construction.
=> docs: add lastmod configuration for sphinx-sitemap

.github/workflows/cla-check.yml, README.md
-----
* add GitHub action from  [canonical/has-signed-canonical-cla](https://www.github.com/canonical/has-signed-canonical-cla) 
* add the CLA requirement in README
=> Add GitHub workflow for checking Contributor Licence Agreement

docs/.sphinx/update_sp.py
The differences have already been calculated and saved in the `new_requirements` variable. It's more efficient to reference the variable rather than recalculating the differences again.
=> Reference an existing variable

docs/how-to/set-up-sitemaps.rst
- n/a
-----
This removes a confusing statement that suggested the SP provided some default sitemap config.
@SecondSkoll, given the doc includes a note (a few lines above this) that says _Sitemap configuration is included in the Starter pack's default configuration file_, I believe there's no need to clarify this confusing statement -- instead, it can be just removed.
=> Remove confusing statement on sitemap config

docs/how-to/rtd.rst
In [Set up Read the Docs](https://canonical-starter-pack.readthedocs-hosted.com/latest/how-to/rtd/) we say:
> If your project was imported from a private repository, your initial build will fail because Read the Docs won't have access to clone the repository. You need to copy your project's private key from Read the Docs and add it as a deploy key to the repository, then re-run the build in Read the Docs.
But it's not the private key that needs to be copied, it's the public key. This PR fixes the doc.
=> docs: fix info about setting RTD key as GitHub deploy key

docs/tutorial/set-up-automated-testing.rst
Spread installed from a snap might not have the correct permissions to run as root, which is required to use the Multipass backend in this tutorial. Therefore, the tutorial needs to be updated warning the user to install Spread via ``go install``.
-----
=> Add warning to set-up-automated-testing.rst

.github/CODEOWNERS, CHANGELOG.md
For #438.
Enumerate individual reviewers. Later, we can add a Sphinx development team, once we've established one.
I've added our most prominent reviewers to review this to check for consent.
**If you'd prefer not to receive review requests on PRs automatically**, please say so, and I'll remove you from the list. :)
---
~~- [ ] Have you updated `CHANGELOG.md` with relevant non-documentation file changes?~~
~~- [ ] Have you updated the documentation for this change?~~
=> chore: add `CODEOWNERS`

docs/conf.py
The preview image being used was an old one, and the design team has suggested the use of this one instead. (MM conversation for reference: https://chat.canonical.com/canonical/pl/wb319fbzotrd7ryj4tj6941i3y)
-----
=> Update Open Graph image URL in conf.py
